"""Initial migration.

Revision ID: 597aeb2d8587
Revises: 
Create Date: 2024-10-29 11:01:34.844336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597aeb2d8587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
